(function(o,m){function h(a){console.dir(a)}function e(a){console.log("--------------- "+a+" ---------------")}function q(a,b,d,c,g){a>b&&(a=b);this.min=a;this.max=b;this.step=d;this.initializer=c;this.callback=g||function(){}}function i(a){this.array=a}function j(a,b,d){this.enumclass=new i(a);this.array=this.enumclass.array;this.initializer=b;this.callback=d||function(){}}function k(a,b,d){this.enumclass=new i(a);this.array=this.enumclass.array;this.initializer=b;this.callback=d||function(){};var d=
d||function(){},c=this;this.enumlinear=new j(a,b,function(a){c.index=c.enumlinear.index;c.value=a;c.history=c.history.concat(c.value);c.array=c.enumlinear.array;d(a,c.app)});for(var g in this.enumlinear)this.enumlinear.hasOwnProperty(g)&&(this[g]=this.enumlinear[g])}function f(a,b,d){this.initializer=b;this.callback=d||function(){};var d=d||function(){},c=this;this.enumlinear=new j(a,function(){b();c.repeat.init();c.shuffle.init();c.enumlinear.init()},function(a,b){e("this.enumlinear callback");h("value: "+
a);c.index=c.enumlinear.index;c.value=a;c.history=c.history.concat(c.value);c.array=c.enumlinear.array;c.enumclass=c.enumlinear.enumclass;d(c.value,b)});this.repeat=new k(["false","true","one"],"false",function(a){h("repeat:"+a)});this.shuffle=new k(["false","true"],"false",function(a){h("shuffle:::"+a);h(c.repeat.value);if(!c.orderedarray)c.orderedarray=c.enumlinear.enumclass.array||c.array||c.enumlinear.array||[];switch(a){case "true":a=(void 0===c.value||0>c.array.indexOf(c.value)?[]:[c.value]).concat(c.orderedarray.shuffle().drop(c.value));
c.changeArray(a);break;default:c.changeArray(c.orderedarray),delete c.orderedarray}});for(var g in this.enumlinear)this.enumlinear.hasOwnProperty(g)&&(this[g]=this.enumlinear[g])}function n(){}(function(){var a=this.Store=function(a,d){var c;this.name=a;if(void 0!==d)for(c in d)d.hasOwnProperty(c)&&void 0===this.get(c)&&this.set(c,d[c])};a.prototype.get=function(a){a="store."+this.name+"."+a;if(null!==localStorage.getItem(a))try{return JSON.parse(localStorage.getItem(a))}catch(d){return null}};a.prototype.set=
function(a,d){if(void 0===d)this.remove(a);else{if("function"===typeof d)d=null;else try{d=JSON.stringify(d)}catch(c){d=null}localStorage.setItem("store."+this.name+"."+a,d)}return this};a.prototype.remove=function(a){localStorage.removeItem("store."+this.name+"."+a);return this};a.prototype.removeAll=function(){var a,d;a="store."+this.name+".";for(d=localStorage.length-1;0<=d;d--)localStorage.key(d).substring(0,a.length)===a&&localStorage.removeItem(localStorage.key(d));return this};a.prototype.toObject=
function(){var a,d,c,g,e;a={};d="store."+this.name+".";for(c=localStorage.length-1;0<=c;c--)localStorage.key(c).substring(0,d.length)===d&&(g=localStorage.key(c).substring(d.length),e=this.get(g),void 0!==e&&(a[g]=e));return a};a.prototype.fromObject=function(a,d){!0!==d&&this.removeAll();for(var c in a)a.hasOwnProperty(c)&&this.set(c,a[c]);return this}})();Array.prototype.clone=function(){return Array.apply(null,this)};Array.prototype.drop=function(a){for(var b=[],d=0;d<this.length;d++)this[d]!==
a&&(b=b.concat([this[d]]));return b};Array.prototype.shuffle=function(){for(var a=this.clone(),b=a.length,d,c,g=Math.random,e=Math.floor;b;)d=e(g()*b),c=a[--b],a[b]=a[d],a[d]=c;return a};Array.prototype.unique=function(){var a=[],b,d,c,e,f;for(b=-1,c=this.length;b<c;++b){for(d=-1,e=a.length,f=!0;d<e;++d)a[d]===this[b]&&(d=e+1,f=!1);f&&a.push(this[b])}return a};if("undefined"!==typeof m&&"undefined"!==typeof m.fn)m.fn.texttitle=function(a){return this.text(a).attr("title",a)},m.fn.unique=Array.prototype.unique,
m.fn.join=Array.prototype.join;if("undefined"!==typeof exports)exports.log=h,exports.logfn=e;var r={strarr:"abcdefghijklmnopqrstuvwxyz",randomstr:function(){for(var a=this.strarr.length,b="",d=0;10>d;d++)b+=this.strarr[Math.floor(Math.random()*a)];return b},createId:function(){return(new Date).getTime().toString()+this.randomstr()},send:function(a){chrome.extension.sendRequest(a)}},p={prevNotification:null,createNotification:function(a,b,d){if(webkitNotifications&&0===webkitNotifications.checkPermission()){this.prevNotification&&
(this.prevNotification.cancel(),delete this.prevNotification);var c=l.getSetting("notification"),e=JSON.parse(l.getSetting("notificationmsec"));if("true"===c){var f=webkitNotifications.createNotification(a,b,d);f.show();setTimeout(function(){f.cancel();delete this.prevNotification},e);this.prevNotification=f}}}};q.prototype={value:void 0,at:function(a){this.value=void 0===a||isNaN(a)?void 0===this.value?(this.min+this.max)/2:this.assert(this.value):this.assert(a);this.callback(this.value,this.app);
return this.value},assert:function(a){return Math.min(Math.max(a,this.min),this.max)},increase:function(a){if(void 0===a||isNaN(a))a=this.step;return this.at(this.value+a)},decrease:function(a){if(void 0===a||isNaN(a))a=this.step;return this.increase(-a)},init:function(a){this.app=a;"function"===typeof this.initializer?this.at(this.initializer()):this.at(this.initializer)},setToMin:function(){return this.at(this.min)},setToMax:function(){return this.at(this.max)}};if("undefined"!==typeof exports)exports.Limited=
q;i.prototype={array:[],succ:function(a){return this.toEnum(1+this.fromEnum(a))},pred:function(a){return this.toEnum(-1+this.fromEnum(a))},toEnum:function(a){if(this.array&&0<=a&&a<this.array.length)return this.array[a]},fromEnum:function(a){if(this.array)for(var b=0,d=this.array.length;b<d;b++)if(this.array[b]===a)return b},enumFrom:function(a){return!this.array?void 0:this.enumFromTo(a,this.array[this.array.length-1])},enumFromThen:function(a,b){if(this.array){for(var d=this.fromEnum(a),c=this.fromEnum(b),
e=[],f=d;0<=f&&f<this.array.length;f+=c-d)e=e.concat(this.array[f]);return e}},enumFromTo:function(a,b){return this.enumFromThenTo(a,this.succ(a),b)},enumFromThenTo:function(a,b,d){if(this.array){var a=this.fromEnum(a),b=this.fromEnum(b),d=this.fromEnum(d),b=b-a,c=[];if(0===b)c=c.concat(this.array[a]);else if(0<b)for(;a<=d&&a<this.array.length;a+=b)c=c.concat(this.array[a]);else for(;a>=d&&0<=a;a+=b)c=c.concat(this.array[a]);return c}}};if("undefined"!==typeof exports)exports.Enum=i;if("undefined"===
typeof o)i=require("./enum").Enum;j.prototype={index:0,value:void 0,history:[],head:function(){e("Enumlinear.prototype.head");return this.at(0)},last:function(){e("Enumlinear.prototype.last");return this.at(this.enumclass.array.length-1)},nonvalidIndex:function(a){return void 0===a||isNaN(a)||"number"!==typeof a},at:function(a){e("Enumlinear.prototype.at");if(this.nonvalidIndex(a))a=this.index;var b=this.enumclass.toEnum(a);if(!(void 0===b||0===this.array.length))return this.value=b,this.index=a,
this.array=this.enumclass.array,this.history=this.history.concat(this.value),this.callback(this.value,this.app),this.value},atfromEnum:function(a){e("Enumlinear.prototype.atfromEnum");console.log("atfromEnum value: "+a);a=this.enumclass.fromEnum(a);return void 0===a?void 0:this.at(a)},next:function(a){e("Enumlinear.prototype.next");this.nonvalidIndex(a)&&(a=1);return this.at(this.index+a)},prev:function(a){e("Enumlinear.prototype.prev");this.nonvalidIndex(a)&&(a=-1);return this.next(a)},init:function(a){e("Enumlinear.prototype.init");
this.app=a;var b;if("function"===typeof this.initializer)try{b=this.initializer()}catch(d){b=this.array[0]}else b=this.initializer;b=this.atfromEnum(b);if(void 0===b)return this.at(0)},concat:function(a){e("Enumlinear.prototype.concat");return this.changeArray(this.enumclass.array.concat(a))},splice:function(a,b){e("Enumlinear.prototype.splice");var d=this.enumclass.array;d.splice(a,b);return this.changeArray(d)},remove:function(a){e("Enumlinear.prototype.remove");console.log("removing : "+a);return this.splice(this.enumclass.fromEnum(a),
1)},changeArray:function(a){e("Enumlinear.prototype.changeArray");console.log(a);a=a.drop(void 0);this.enumclass=new i(a);this.array=this.enumclass.array;this.at(this.enumclass.fromEnum(this.value)||0);return this}};if("undefined"!==typeof exports)exports.Enumlinear=j;if("undefined"===typeof o)i=require("./enum").Enum,j=require("./enumlinear").Enumlinear;k.prototype=new j;k.prototype.at=function(a){if(this.nonvalidIndex(a))a=this.index;var b=this.array.length;return this.enumlinear.at((a%b+b)%b)};
k.prototype.changeArray=function(a){this.enumlinear.changeArray(a);this.array=this.enumlinear.array;this.enumclass=this.enumlinear.enumclass};if("undefined"!==typeof exports)exports.Enumcycle=k;if("undefined"===typeof o)require("./prelude"),i=require("./enum").Enum,j=require("./enumlinear").Enumlinear,k=require("./enumcycle").Enumcycle;f.prototype=new j;f.prototype.at=function(a){e("Enumdinamic.prototype.at");if(this.nonvalidIndex(a))a=this.index;h("this:::");return this.enumlinear.at(a)};f.prototype.next=
function(a){e("Enumdinamic.prototype.next");if(void 0===a||isNaN(a))a=1;a=void 0===this.index?0:this.index+a;switch(this.repeat.value){case "one":a=this.index;break;case "true":var b=this.enumclass.toEnum(a);if(void 0===b)switch(this.shuffle.value){case "true":this.shuffleOn(),a++;default:b=this.array.length,a=(a%b+b)%b}break;default:if(b=this.enumclass.toEnum(a),void 0===b)switch(this.shuffle.value){case "true":this.shuffleOn();default:return}}return this.at(a)};f.prototype.concat=function(a){e("Enumdinamic.prototype.concat");
var b=this.array||[];this.orderedarray=(this.orderedarray||this.array||[]).concat(a);this.changeArray(b.concat(a));"true"===this.shuffle.value&&this.shuffleOn()};f.prototype.remove=function(a){h(this);e("Enumdinamic.prototype.remove");if(this.orderedarray)this.orderedarray=this.orderedarray.drop(a);this.enumlinear.remove(a);h(this)};f.prototype.changeArray=function(a){e("Enumdinamic.prototype.changeArray");h(this.value);a=a.drop(void 0);this.enumlinear.changeArray(a);this.array=this.enumlinear.array;
h("this.array: "+this.array.join(","));h("this.value: "+this.value);this.enumclass=this.enumlinear.enumclass;this.atfromEnum(this.value);for(var b in this.enumlinear)this.enumlinear.hasOwnProperty(b)&&(this[b]=this.enumlinear[b]);return this};f.prototype.setRepeat=function(a){this.repeat.atfromEnum(a)};f.prototype.repeatOff=function(){this.setRepeat("false")};f.prototype.repeatOn=function(){this.setRepeat("true")};f.prototype.repeatOne=function(){this.setRepeat("one")};f.prototype.repeatToggle=function(){this.repeat.next()};
f.prototype.repeatToggleOnOff=function(){this.setRepeat("false"===this.repeat.value?"true":"false")};f.prototype.setShuffle=function(a){this.shuffle.atfromEnum(a)};f.prototype.shuffleOff=function(){this.setShuffle("false")};f.prototype.shuffleOn=function(){this.setShuffle("true")};f.prototype.shuffleToggle=function(){this.shuffle.next()};f.prototype.shuffleToggleOnOff=function(){this.setShuffle("false"===this.shuffle.value?"true":"false")};if("undefined"!==typeof exports)exports.Enumdinamic=f;var l=
{get:function(a){return localStorage.getItem(a)},set:function(a,b){localStorage.setItem(a,b)},remove:function(a){localStorage.removeItem(a)},clear:function(){localStorage.clear()},getSetting:function(a){return l.get("store.settings."+a)},getSettingParse:function(a){return JSON.parse(l.get("store.settings."+a))}};n.prototype={start:function(){p.createNotification("../icon_128.png","Local Player","Background page created");for(var a in this)if(this[a]&&this[a].init)this[a].init(this),this[a].app=this,
h("init: "+a)}};n.prototype.message={init:function(){chrome.extension.onRequest.addListener(function(a){console.dir(a);switch(a.type){case "notification":p.createNotification(a.icon,a.title,a.message);break;case "globalkeydown":h(a);var b=l.getSetting("globalcontrol");if(void 0===b||"false"===b)break;a.type="globalkeydown-bg";r.send(a);break;case "get-globalkeybind":r.send({type:"ans-globalkeybind",ans:"",to:a.from})}})}};n.prototype.setting={defaultSetting:{notification:!0,notificationmsec:5E3,globalcontrol:!0,
scheme:"classic-default",playerrc:"\n# This is configuration of Local Player\n\n# Vim like keymappings\nmap j <down>\nmap k <up>\nmap gg <home>\nmap <s-g> <end>\nmap <c-f> PageDown\nmap <c-b> PageUp\n\n\n\nmap m VolumeToggleMute\nmap <rd> RemoveDuplicated\nmap <c-j> Nop\nmap <c-h> Nop\n\n# unmap keybind registered once\nunmap f\n\n# do not import musics matching regular expression\navoid /[iI]nstrument|[oO]ff vocal|([rR]e)?mix/\n\n"},init:function(){this.settings=new Store("settings",this.defaultSetting)},
reset:function(){this.settings.fromObject(this.defaultSetting)}};n.prototype.version={toString:function(){return"2.0"},init:function(a){this.app=a;var b=this.app.version.toString();this.app.version.notify(l.get("version")!==b);setTimeout(function(){l.set("version",b)},1E3)},notify:function(a){a&&p.createNotification("../icon_128.png","Local Player","Updated to version "+this.app.version)}};var s=new n;o.onload=function(){s.start()};this.resetSettings=function(){s.setting.reset()};e=function(){};h=
function(){}})(this,"undefined"!==typeof jQuery?jQuery:{});
