(function(n,l){function h(a){console.dir(a)}function f(a){console.log("--------------- "+a+" ---------------")}function q(a,b,d,c,g){a>b&&(a=b);this.min=a;this.max=b;this.step=d;this.initializer=c;this.callback=g||function(){}}function i(a){this.array=a}function j(a,b,d){this.enumclass=new i(a);this.array=this.enumclass.array;this.initializer=b;this.callback=d||function(){}}function k(a,b,d){this.enumclass=new i(a);this.array=this.enumclass.array;this.initializer=b;this.callback=d||function(){};var d=
d||function(){},c=this;this.enumlinear=new j(a,b,function(a){c.index=c.enumlinear.index;c.value=a;c.history=c.history.concat(c.value);c.array=c.enumlinear.array;d(a,c.app)});for(var g in this.enumlinear)this.enumlinear.hasOwnProperty(g)&&(this[g]=this.enumlinear[g])}function e(a,b,d){this.initializer=b;this.callback=d||function(){};var d=d||function(){},c=this;this.enumlinear=new j(a,function(){b();c.repeat.init();c.shuffle.init();c.enumlinear.init()},function(a,b){f("this.enumlinear callback");h("value: "+
a);c.index=c.enumlinear.index;c.value=a;c.history=c.history.concat(c.value);c.array=c.enumlinear.array;c.enumclass=c.enumlinear.enumclass;d(c.value,b)});this.repeat=new k(["false","true","one"],"false",function(a){console.log("repeat:"+a)});this.shuffle=new k(["false","true"],"false",function(a){console.log("shuffle:::"+a);h(c.repeat.value);if(!c.orderedarray)c.orderedarray=c.enumlinear.enumclass.array||c.array||c.enumlinear.array||[];switch(a){case "true":a=(void 0===c.value||0>c.array.indexOf(c.value)?
[]:[c.value]).concat(c.orderedarray.shuffle().drop(c.value));c.changeArray(a);break;default:c.changeArray(c.orderedarray),delete c.orderedarray}});for(var g in this.enumlinear)this.enumlinear.hasOwnProperty(g)&&(this[g]=this.enumlinear[g])}function o(){}Array.prototype.clone=function(){return Array.apply(null,this)};Array.prototype.drop=function(a){for(var b=[],d=0;d<this.length;d++)this[d]!==a&&(b=b.concat([this[d]]));return b};Array.prototype.shuffle=function(){for(var a=this.clone(),b=a.length,
d,c,g=Math.random,f=Math.floor;b;)d=f(g()*b),c=a[--b],a[b]=a[d],a[d]=c;return a};Array.prototype.unique=function(){var a=[],b,d,c,f,e;for(b=-1,c=this.length;b<c;++b){for(d=-1,f=a.length,e=!0;d<f;++d)a[d]===this[b]&&(d=f+1,e=!1);e&&a.push(this[b])}return a};if("undefined"!==typeof l&&"undefined"!==typeof l.fn)l.fn.texttitle=function(a){return this.text(a).attr("title",a)},l.fn.unique=Array.prototype.unique,l.fn.join=Array.prototype.join;if("undefined"!==typeof exports)exports.log=h,exports.logfn=f;
var p={prevNotification:null,createNotification:function(a,b,d){if(webkitNotifications&&0===webkitNotifications.checkPermission()){this.prevNotification&&(this.prevNotification.cancel(),delete this.prevNotification);var c=m.getSetting("notification"),f=JSON.parse(m.getSetting("notificationmsec"));if("true"===c){var e=webkitNotifications.createNotification(a,b,d);e.show();setTimeout(function(){e.cancel();delete this.prevNotification},f);this.prevNotification=e}}}};q.prototype={value:void 0,at:function(a){this.value=
void 0===a||isNaN(a)?void 0===this.value?(this.min+this.max)/2:this.assert(this.value):this.assert(a);this.callback(this.value,this.app);return this.value},assert:function(a){return Math.min(Math.max(a,this.min),this.max)},increase:function(a){if(void 0===a||isNaN(a))a=this.step;return this.at(this.value+a)},decrease:function(a){if(void 0===a||isNaN(a))a=this.step;return this.increase(-a)},init:function(a){this.app=a;"function"===typeof this.initializer?this.at(this.initializer()):this.at(this.initializer)},
setToMin:function(){return this.at(this.min)},setToMax:function(){return this.at(this.max)}};if("undefined"!==typeof exports)exports.Limited=q;i.prototype={array:[],succ:function(a){return this.toEnum(1+this.fromEnum(a))},pred:function(a){return this.toEnum(-1+this.fromEnum(a))},toEnum:function(a){if(this.array&&0<=a&&a<this.array.length)return this.array[a]},fromEnum:function(a){if(this.array)for(var b=0,d=this.array.length;b<d;b++)if(this.array[b]===a)return b},enumFrom:function(a){return!this.array?
void 0:this.enumFromTo(a,this.array[this.array.length-1])},enumFromThen:function(a,b){if(this.array){for(var d=this.fromEnum(a),c=this.fromEnum(b),f=[],e=d;0<=e&&e<this.array.length;e+=c-d)f=f.concat(this.array[e]);return f}},enumFromTo:function(a,b){return this.enumFromThenTo(a,this.succ(a),b)},enumFromThenTo:function(a,b,d){if(this.array){var a=this.fromEnum(a),b=this.fromEnum(b),d=this.fromEnum(d),b=b-a,c=[];if(0===b)c=c.concat(this.array[a]);else if(0<b)for(;a<=d&&a<this.array.length;a+=b)c=c.concat(this.array[a]);
else for(;a>=d&&0<=a;a+=b)c=c.concat(this.array[a]);return c}}};if("undefined"!==typeof exports)exports.Enum=i;if("undefined"===typeof n)i=require("./enum").Enum;j.prototype={index:0,value:void 0,history:[],head:function(){f("Enumlinear.prototype.head");return this.at(0)},last:function(){f("Enumlinear.prototype.last");return this.at(this.enumclass.array.length-1)},nonvalidIndex:function(a){return void 0===a||isNaN(a)||"number"!==typeof a},at:function(a){f("Enumlinear.prototype.at");if(this.nonvalidIndex(a))a=
this.index;var b=this.enumclass.toEnum(a);if(!(void 0===b||0===this.array.length))return this.value=b,this.index=a,this.array=this.enumclass.array,this.history=this.history.concat(this.value),this.callback(this.value,this.app),this.value},atfromEnum:function(a){f("Enumlinear.prototype.atfromEnum");console.log("atfromEnum value: "+a);a=this.enumclass.fromEnum(a);return void 0===a?void 0:this.at(a)},next:function(a){f("Enumlinear.prototype.next");this.nonvalidIndex(a)&&(a=1);return this.at(this.index+
a)},prev:function(a){f("Enumlinear.prototype.prev");this.nonvalidIndex(a)&&(a=-1);return this.next(a)},init:function(a){f("Enumlinear.prototype.init");this.app=a;var b;if("function"===typeof this.initializer)try{b=this.initializer()}catch(d){b=this.array[0]}else b=this.initializer;b=this.atfromEnum(b);if(void 0===b)return this.at(0)},concat:function(a){f("Enumlinear.prototype.concat");return this.changeArray(this.enumclass.array.concat(a))},splice:function(a,b){f("Enumlinear.prototype.splice");var d=
this.enumclass.array;d.splice(a,b);return this.changeArray(d)},remove:function(a){f("Enumlinear.prototype.remove");console.log("removing : "+a);return this.splice(this.enumclass.fromEnum(a),1)},changeArray:function(a){f("Enumlinear.prototype.changeArray");console.log(a);this.enumclass=new i(a);this.array=this.enumclass.array;this.at(this.enumclass.fromEnum(this.value)||0);return this}};if("undefined"!==typeof exports)exports.Enumlinear=j;if("undefined"===typeof n)i=require("./enum").Enum,j=require("./enumlinear").Enumlinear;
k.prototype=new j;k.prototype.at=function(a){if(this.nonvalidIndex(a))a=this.index;var b=this.array.length;return this.enumlinear.at((a%b+b)%b)};k.prototype.changeArray=function(a){this.enumlinear.changeArray(a);this.array=this.enumlinear.array;this.enumclass=this.enumlinear.enumclass};if("undefined"!==typeof exports)exports.Enumcycle=k;if("undefined"===typeof n)require("./prelude"),i=require("./enum").Enum,j=require("./enumlinear").Enumlinear,k=require("./enumcycle").Enumcycle;e.prototype=new j;
e.prototype.at=function(a){f("Enumdinamic.prototype.at");if(this.nonvalidIndex(a))a=this.index;h("this:::");return this.enumlinear.at(a)};e.prototype.next=function(a){f("Enumdinamic.prototype.next");if(void 0===a||isNaN(a))a=1;a=void 0===this.index?0:this.index+a;switch(this.repeat.value){case "one":a=this.index;break;case "true":var b=this.enumclass.toEnum(a);if(void 0===b)switch(this.shuffle.value){case "true":this.shuffleOn(),a++;default:b=this.array.length,a=(a%b+b)%b}break;default:if(b=this.enumclass.toEnum(a),
void 0===b)switch(this.shuffle.value){case "true":this.shuffleOn();default:return}}return this.at(a)};e.prototype.concat=function(a){f("Enumdinamic.prototype.concat");var b=this.array||[];this.orderedarray=(this.orderedarray||this.array||[]).concat(a);this.changeArray(b.concat(a));"true"===this.shuffle.value&&this.shuffleOn()};e.prototype.remove=function(a){f("Enumdinamic.prototype.remove");if(this.orderedarray)this.orderedarray=this.orderedarray.drop(a);this.enumlinear.remove(a)};e.prototype.changeArray=
function(a){f("Enumdinamic.prototype.changeArray");h(this.value);this.enumlinear.changeArray(a);this.array=this.enumlinear.array;h("this.array: "+this.array.join(","));h("this.value: "+this.value);this.enumclass=this.enumlinear.enumclass;this.atfromEnum(this.value);for(var b in this.enumlinear)this.enumlinear.hasOwnProperty(b)&&(this[b]=this.enumlinear[b]);return this};e.prototype.setRepeat=function(a){this.repeat.atfromEnum(a)};e.prototype.repeatOff=function(){this.setRepeat("false")};e.prototype.repeatOn=
function(){this.setRepeat("true")};e.prototype.repeatOne=function(){this.setRepeat("one")};e.prototype.repeatToggle=function(){this.repeat.next()};e.prototype.repeatToggleOnOff=function(){this.setRepeat("false"===this.repeat.value?"true":"false")};e.prototype.setShuffle=function(a){this.shuffle.atfromEnum(a)};e.prototype.shuffleOff=function(){this.setShuffle("false")};e.prototype.shuffleOn=function(){this.setShuffle("true")};e.prototype.shuffleToggle=function(){this.shuffle.next()};e.prototype.shuffleToggleOnOff=
function(){this.setShuffle("false"===this.shuffle.value?"true":"false")};if("undefined"!==typeof exports)exports.Enumdinamic=e;var m={get:function(a){return localStorage.getItem(a)},set:function(a,b){localStorage.setItem(a,b)},remove:function(a){localStorage.removeItem(a)},clear:function(){localStorage.clear()},getSetting:function(a){return m.get("store.settings."+a)}};o.prototype={start:function(){p.createNotification("../icon_128.png","Local Player","Background page created");for(var a in this)this[a]&&
this[a].init&&(this[a].init(this),h("init: "+a))},message:{init:function(a){this.app=a;chrome.extension.onRequest.addListener(function(a){switch(a.type){case "notification":p.createNotification(a.icon,a.title,a.message)}})}}};o.prototype.version={toString:function(){return"2.0"},init:function(a){this.app=a;var b=this.app.version.toString();this.app.version.notify(m.get("version")!==b);setTimeout(function(){m.set("version",b)},1E3)},notify:function(a){a&&p.createNotification("../icon_128.png","Local Player",
"Updated to version "+this.app.version)}};var r=new o;n.onload=function(){r.start()};f=function(){};h=function(){}})(this,"undefined"!==typeof jQuery?jQuery:{});
