SOURCE_FILES =\
	header.js \
	prelude.js \
	limited.js \
	enumclass.js \
	enumstate.js \
	id3.js \
	music.js \
	local.js \
	schemeconfig.js \
	ui.js \
	order.js \
	key.js \
	keyconfig.js \
	player.js \
	footer.js


main.js : ${SOURCE_FILES} makefile
	@cat ${SOURCE_FILES} > main.js

all:
	make main.js

